<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-VIEGQI7" failures="1" tests="2" name="smoke" time="9.041" errors="0" timestamp="2024-10-19T12:15:40 MESZ">
  <testcase classname="automationP.testcases.GUI" name="tc_1" time="0.37">
    <skipped/>
  </testcase> <!-- tc_1 -->
  <testcase classname="automationP.testcases.GUI" name="tc_1" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at automationP.testcases.GUI.tc_1(GUI.java:24)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- tc_1 -->
  <testcase classname="automationP.testcases.GUI" name="tc_6" time="0.0">
    <ignored/>
  </testcase> <!-- tc_6 -->
  <testcase classname="automationP.testcases.GUI" name="tc_4" time="0.0">
    <ignored/>
  </testcase> <!-- tc_4 -->
  <testcase classname="automationP.testcases.GUI" name="tc_5" time="0.0">
    <ignored/>
  </testcase> <!-- tc_5 -->
  <testcase classname="automationP.testcases.GUI" name="tc_2" time="0.0">
    <ignored/>
  </testcase> <!-- tc_2 -->
  <testcase classname="automationP.testcases.GUI" name="tc_3" time="0.0">
    <ignored/>
  </testcase> <!-- tc_3 -->
</testsuite> <!-- smoke -->
